### ISSUE TITLE
Error in Projects Page!

### ISSUE THREAD

**Issue by 34534206** [markdino/Construction-website-1#27]
I cloned and tried to run the app but error below pop out when i try to browse projects page!!! I tried to figure out but don't know what's causing the problem??

![error](https://user-images.githubusercontent.com/66189342/86712380-abbbbe00-c03c-11ea-98ad-c7a9c37edc07.png)

![error1](https://user-images.githubusercontent.com/66189342/86712388-ae1e1800-c03c-11ea-8eac-08e246490275.png)

![error](https://user-images.githubusercontent.com/66189342/86711382-9e520400-c03b-11ea-9842-3fe93333766b.png)

**Comment by markdino** [comment]
Hi @34534206 
Did you make some changes in the codes?
This codes should work fine. 

You can check the live preview of this code [here](https://construction1-gatsbytemplate-markdino.netlify.app/)
